export const skillSet = {
  languages: [
    { name: 'HTML5', iconName: 'html5' },
    { name: 'CSS3', iconName: 'css3' },
    { name: 'Javascript', iconName: 'javascript' },
    { name: 'Typescript', iconName: 'typescript' },
    { name: 'Python', iconName: 'python' },
    { name: 'PHP', iconName: 'php' },
  ],
  tools: [
    { name: 'React', iconName: 'react' },
    { name: 'Next.js', iconName: 'nextjs' },
    { name: 'Redux', iconName: 'redux' },
    { name: 'Material UI', iconName: 'materialui' },
    { name: 'styled-components', iconName: 'styledcomponents' },
    { name: 'Git', iconName: 'git' },
  ],
  databases: [
    { name: 'MySQL', iconName: 'mysql' },
    { name: 'PostgreSQL', iconName: 'postgresql' },
    { name: 'MongoDB', iconName: 'mongodb' },
    { name: 'Firebase', iconName: 'firebase' },
    { name: 'Sanity', iconName: 'sanity' },
  ],
  others: [
    { name: 'Node.js', iconName: 'nodejs' },
    { name: 'Express', iconName: 'express' },
    { name: 'Chart.js', iconName: '' },
    { name: 'Leaflet (map)', iconName: '' },
    { name: 'Framer Motion (animation)', iconName: '' },
    { name: 'Django', iconName: 'django' },
    { name: 'FastAPI', iconName: '' },
    { name: 'Pandas', iconName: 'pandas' },
    // { name: 'Matlab', iconName: 'Matlab' },
    { name: 'PyQt', iconName: '' },
    { name: 'Scrapy.py', iconName: '' },
    { name: 'Linux ', iconName: 'linux' },
    { name: 'Bash', iconName: 'bash' },
    { name: 'Chrome Extension', iconName: '' },
    { name: 'Vercel', iconName: '' },
    { name: 'Netlify', iconName: '' },
  ],
};
